### ISSUE TITLE
Question: Could this library be used instead of apollo-client?

### ISSUE THREAD

**Issue by CharlyJazz** [arackaf/micro-graphql-react#6]
Should this library / tool be used when we have a React application without apollo-client and we want to interact with a GraphQL interface?

**Comment by arackaf** [comment]
Hi.  I'm afraid I'm not an expert in Apollo, but I have experimented with it.

Apollo has a much richer caching mechanism.  It far exceeds what mine library will have even after I update it to have better caching.

That said, it works with POST only, so no service worker caching, and it's significantly larger.

And of course Apollo is much, much more stable than this.

I'd recommend you try both and see what you feel most comfortable with.

**Comment by evans** [comment]
@arackaf Interesting idea for service worker caching!

It turns out that Apollo Client's new network interface Apollo Link [supports GET requests](https://www.apollographql.com/docs/link/links/http.html#get-request). We definitely need to make the documentation more accessible. Thank you for pointing out the issue!

I think a link(apollo-link-sw-cache?) that changes compatible queries to GET requests and forwards to the http link would be an incredible addition to the ecosystem. Are you interested in creating it or collaborating on the design?

**Comment by arackaf** [comment]
Possibly, but I'm not sure this is something that should be done automatically.  If you're caching gql queries with a service worker, the onus is now on you to perform whatever cache busting you need.  I do it with something along the lines of 

```javascript
let query = `query Read_Stuff_${version} {
  allThings{
    Thing { _id, name }
  }
}`
```

where version is store in my Redux store somewhere, and auto-incremented whenever an action comes through that mutates any of the data in question.  So when that changes, the query url is now different, and won't hit anything prior in the service worker.

Devs need to be deliberate with how they set up their service worker / what they cache with it, else they may wind up breaking the user's refresh button.

**Comment by jaydenseric** [comment]
It looks like this library by nature does not support server side rendering and client side hydration? That would be the biggest consideration.

**Comment by arackaf** [comment]
Honestly not sure - I've never done SSR before.  The query is fired in componentDidMount - not sure how that affects SSR.

**Comment by jaydenseric** [comment]
Tricky things to support SSR:

* Getting the queries to fetch, since `componentDidMount` does not happen in React's `renderToString`. If queries are defined in components you have to do a render to walk the component tree, run all the queries and populate a cache of the results. `react-apollo` does this; I haven't used it yet but [`react-tree-walker`](https://github.com/ctrlplusb/react-tree-walker) might save you a lot of trouble implementation. Then you have to do a second render (for real this time) using the cached results. Otherwise the server side rendered HTML will just show all your loading states.
* The server needs to pass the cache, serialize as JSON, to the client.
* On the client, you need to hydrate your queries with the cache. Otherwise React will think there is a render mismatch between the SSR HTML and the first client render, wish would immediately show loading states and attempt to fetch all the queries.

In regards to this library, I'm not sure how easy it is to serialize HTTP caching so it can be passed from the server to the client for hydration.

**Comment by arackaf** [comment]
If SSR is a hard requirement for you, I'd definitely recommend Apollo.  This likely won't be the library for you :)

**Comment by arackaf** [comment]
Closing but if you have anything to add, feel free

**Comment by loganpowell** [comment]
This is interesting. Could you provide an example of using `micro-graphql-react` in concert with a service worker?
